site_name: MarketWatch API

theme:
  name: material
  palette:
    primary: blue
    accent: blue

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Explanation: explanation.md
  - Examples: examples.md
  - API Reference: api.md
  - Tutorials: tutorials.md
  - Reference: reference.md
  - Contacts: contacts.md
