site_name: MarketWatch API

theme:
  name: material
  palette:
    primary: blue
    accent: blue

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - API: api.md
  - Examples: examples.md
  - About: about.md
  - Reference: reference.md