name: Python Docs

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    branches:
      - feature/*
      - main
    paths:
      - 'docs/**'

permissions:
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for changes in /docs
        id: check_changes
        run: |
          git fetch origin ${{ github.event.before }} # Fetch the base commit
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- docs/)
          if [[ -n "$CHANGED_FILES" ]]; then
            echo "Changes detected in docs folder."
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes in docs folder."
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Set up Python 3.8
        if: env.changes_detected == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        if: env.changes_detected == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install mkdocs

      - name: Test with doctest
        if: env.changes_detected == 'true'
        run: |
          echo "python -m doctest marketwatch/*.py"
          
      - name: Build mkdocs
        if: env.changes_detected == 'true'
        run: |
          mkdocs build

      - name: Archive site
        if: env.changes_detected == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

      - name: Configure Git
        if: env.changes_detected == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Deploy to GitHub Pages
        if: env.changes_detected == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          publish_branch: gh_pages
          publish_dir: site
