name: Python Docs

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install mkdocs
      - name: Test with doctest
        run: |
          echo "python -m doctest marketwatch/*.py"
      - name: Build mkdocs
        run: |
          mkdocs build
      - name: Archive site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: site
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          BRANCH: gh-pages
          FOLDER: site
