name: Python Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  MARKETWATCH_USERNAME: ${{ secrets.MARKETWATCH_USERNAME }}
  MARKETWATCH_PASSWORD: ${{ secrets.MARKETWATCH_PASSWORD }}

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry genbadge[coverage] defusedxml
          poetry install
      - name: Export Environment Variables
        shell: bash
        run: |
          echo "MARKETWATCH_USERNAME=${MARKETWATCH_USERNAME}" >> $GITHUB_ENV
          echo "MARKETWATCH_PASSWORD=${MARKETWATCH_PASSWORD}" >> $GITHUB_ENV
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Build package
        run: poetry build
      - name: Coverage
        run: poetry run pytest --cov=marketwatch --cov-report=xml --cov-report=html
      - name: genbadge coverage
        if: matrix.os == 'ubuntu-latest'
        run: genbadge coverage -o .github/badge/coverage.svg -i coverage.xml
      - name: Upload Artifact to Github HTML
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverageHTML
          path: htmlcov
      - name: Upload Artifact to Github XML
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverageXML
          path: coverage.xml
      - name: Upload coverage reports to Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
