# write github actions for python test

name: Python Test and Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.10"
  MARKETWATCH_USERNAME: ${{ secrets.MARKETWATCH_USERNAME }}
  MARKETWATCH_PASSWORD: ${{ secrets.MARKETWATCH_PASSWORD }}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry genbadge[coverage] defusedxml
          poetry install
      - name: Export Environment Variables
        run: |
          echo "MARKETWATCH_USERNAME=${MARKETWATCH_USERNAME}" >> $GITHUB_ENV
          echo "MARKETWATCH_PASSWORD=${MARKETWATCH_PASSWORD}" >> $GITHUB_ENV
          export MARKETWATCH_USERNAME
          export MARKETWATCH_PASSWORD
      - name: Test with pytest
        run: |
          poetry run pytest
      - name: Build package
        run: poetry build
      - name: Coverage
        run: poetry run pytest --cov=marketwatch --cov-report=xml --cov-report=html
      - name: genbadge coverage
        run: genbadge coverage -o .github/badge/coverage.svg -i coverage.xml
      - name: Upload Artifact to Github HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverageHTML
          path: htmlcov
      - name: Upload Artifact to Github XML
        uses: actions/upload-artifact@v3
        with:
          name: coverageXML
          path: coverage.xml
